-- (password is 'password123')
INSERT INTO users (username, password, email) VALUES
                                                  ('player1', '$2a$10$EA3O2M3MhvKg5/QLwzIkAu5b9/ZrPgrdlQ2mE/A3XJu48Afv3CDzG', 'player1@email.com'),
                                                  ('player2', '$2a$10$EA3O2M3MhvKg5/QLwzIkAu5b9/ZrPgrdlQ2mE/A3XJu48Afv3CDzG', 'player2@email.com'),
                                                  ('player3', '$2a$10$EA3O2M3MhvKg5/QLwzIkAu5b9/ZrPgrdlQ2mE/A3XJu48Afv3CDzG', 'player3@email.com'),
                                                  ('champion', '$2a$10$EA3O2M3MhvKg5/QLwzIkAu5b9/ZrPgrdlQ2mE/A3XJu48Afv3CDzG', 'champion@email.com'),
                                                  ('gamer123', '$2a$10$EA3O2M3MhvKg5/QLwzIkAu5b9/ZrPgrdlQ2mE/A3XJu48Afv3CDzG', 'gamer123@email.com');

INSERT INTO words (word, length, difficulty) VALUES
                                                ('HOUSE', 5, 1),
                                                ('BASIC', 5, 1),
                                                ('SMILE', 5, 1),
                                                ('APPLE', 5, 1),
                                                ('CHAIR', 5, 1),
                                                ('BEACH', 5, 1),
                                                ('DREAM', 5, 1),
                                                ('PAPER', 5, 1),
                                                ('TABLE', 5, 1),
                                                ('WATER', 5, 1),
                                                ('HAPPY', 5, 1),
                                                ('CLOUD', 5, 1),
                                                ('LIGHT', 5, 1),
                                                ('MUSIC', 5, 1),
                                                ('BREAD', 5, 1),
                                                ('PLANT', 5, 1),
                                                ('RADIO', 5, 1),
                                                ('PHONE', 5, 1),
                                                ('WORLD', 5, 1),
                                                ('MONEY', 5, 1),
                                                ('BRAIN', 5, 1),
                                                ('DANCE', 5, 1),
                                                ('HEART', 5, 1),
                                                ('PYTHON', 6, 2),
                                                ('SPRING', 6, 2),
                                                ('CODING', 6, 2),
                                                ('ANGULAR', 7, 2),
                                                ('SUNSET', 6, 2),
                                                ('GARDEN', 6, 2),
                                                ('ROCKET', 6, 2),
                                                ('PLANET', 6, 2),
                                                ('FOREST', 6, 2),
                                                ('WINTER', 6, 2),
                                                ('SUMMER', 6, 2),
                                                ('CANVAS', 6, 2),
                                                ('SIGNAL', 6, 2),
                                                ('STREAM', 6, 2),
                                                ('BUTTON', 6, 2),
                                                ('RHYTHM', 6, 2),
                                                ('NETWORK', 7, 2),
                                                ('COUNTRY', 7, 2),
                                                ('LIBRARY', 7, 2),
                                                ('DOCKER', 6, 3),
                                                ('KUBERNETES', 10, 3),
                                                ('JAVASCRIPT', 10, 3);

-- (random scores between 50-1000)
INSERT INTO scores (score, user_id, word_id, date_time) VALUES
                                                            (850, 1, 1, '2024-02-15 10:30:00'),
                                                            (920, 1, 3, '2024-02-16 11:20:00'),
                                                            (750, 2, 2, '2024-02-15 14:15:00'),
                                                            (680, 2, 4, '2024-02-17 16:45:00'),
                                                            (950, 3, 5, '2024-02-18 09:30:00'),
                                                            (590, 3, 6, '2024-02-19 13:20:00'),
                                                            (780, 4, 7, '2024-02-20 15:10:00'),
                                                            (830, 4, 8, '2024-02-21 17:30:00'),
                                                            (990, 5, 9, '2024-02-22 12:00:00'),
                                                            (880, 5, 10, '2024-02-23 14:40:00'),
                                                            (760, 1, 5, '2024-02-24 10:15:00'),
                                                            (840, 2, 7, '2024-02-25 11:45:00'),
                                                            (910, 3, 8, '2024-02-26 16:20:00'),
                                                            (730, 4, 9, '2024-02-27 13:50:00'),
                                                            (870, 5, 1, '2024-02-28 15:30:00');